//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public string AddressInfo { get; set; }
        public string Postcode { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string AddressType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CustomerID { get; set; }
        public string Areas { get; set; }
        public string AddressName { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
