//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeatil
    {
        public int DetialID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProperID { get; set; }
        public string ProductName { get; set; }
        public string TypeName { get; set; }
        public string ProperName { get; set; }
        public string IMG { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductProperty ProductProperty { get; set; }
    }
}
