//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDeatils = new HashSet<OrderDeatil>();
        }
    
        public int OrderID { get; set; }
        public string OrderState { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string SenDate { get; set; }
        public string RecevieDate { get; set; }
        public string AddressInfo { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceType { get; set; }
        public Nullable<decimal> Postage { get; set; }
        public string Express { get; set; }
        public string ExpressNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDeatil> OrderDeatils { get; set; }
    }
}
